In [10]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
df = pd.read_csv('train.txt',sep=";",header=None,names=['text','emotion'])
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [12]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [13]:
unique_emotions = df['emotion'].unique()
emotion_numbers = {}
i=0
for emo in unique_emotions:
    emotion_numbers[emo] = i
    i+=1
df['emotion'] = df['emotion'].map(emotion_numbers)
df

                                                    text  emotion
0                                i didnt feel humiliated        0
1      i can go from feeling so hopeless to so damned...        0
2       im grabbing a minute to post i feel greedy wrong        1
3      i am ever feeling nostalgic about the fireplac...        2
4                                   i am feeling grouchy        1
...                                                  ...      ...
15995  i just had a very brief time in the beanbag an...        0
15996  i am now turning and i feel pathetic that i am...        0
15997                     i feel strong and good overall        5
15998  i feel like this was such a rude comment and i...        1
15999  i know a lot but i feel so stupid because i ca...        0

[16000 rows x 2 columns]

In [14]:
df['text'] = df['text'].apply(lambda x : x.lower())

In [15]:
import string

def remove_pinc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))

df['text'] = df['text'].apply(remove_pinc)